### PR TITLE
git and github added

### PR DESCRIPTION
**Pull request by Pratham-Mishra178**
issue #6

### CODE REVIEW

**Review by Jassi10000-zz — COMMENTED** [review]
@Pratham-Mishra178 Buddy it would be nice if you follow the right steps to contribute to an open source project 
Pls open an issue first , mention what you want to do or what you want to contribute 
If we lack that in our resource , I will assign it to you , after working you can send a PR mentioning the issue no on which you got assigned and  most important add description in PR section what you did ,what changes you made

I hope you will follow this and learn some good ways to be a nice contributor 😊

**Comment by Pratham-Mishra178** [comment]
> @Pratham-Mishra178 Buddy it would be nice if you follow the right steps to contribute to an open source project
> Pls open an issue first , mention what you want to do or what you want to contribute
> If we lack that in our resource , I will assign it to you , after working you can send a PR mentioning the issue no on which you got assigned and most important add description in PR section what you did ,what changes you made
> 
> I hope you will follow this and learn some good ways to be a nice contributor 😊

sure

**Review by Jassi10000-zz — APPROVED** [review]
Thanks for your contribution @Pratham-Mishra178

**Comment by Pratham-Mishra178** [comment]
> Thanks for your contribution @Pratham-Mishra178

it my pleasure

**Pull request merged**
